version: '3.8'

services:

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongo-container
    volumes:
      - servo-db:/data/db
    restart: always
    ports:
      - 27017:27017
    # image: mysql:latest
    # volumes:
    #   - servo-db:/var/lib/mysql
    # restart:
    #   always
    # environment:
    #   # MYSQL_USER: root
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: servo
    # ports:
    #   - "3307:3307"

    # adminer:
    #   image: adminer:latest
    #   restart: always
    #   ports:
    #     - "8080:8080"
    #   environment:
    #     - ADMINER_PLUGINS=mongodb
  mongo-exp:
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-container
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
    ports:
      - '8081:8081'
  bot:
    build:
      dockerfile: Dockerfile
    image: sweetcapitan/servo:latest
    depends_on:
      - mongo
    # environment: 

volumes:
  servo-db:
