version: '3.8'

services:

  database:
    image: mysql:latest
    volumes:
      - servo-db:/var/lib/mysql
    restart:
      always
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servo
    ports:
      - "3306:3306"
  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #     - "8080:8080"
  bot:
    build:
      dockerfile: Dockerfile
    image: sweetcapitan/servo:latest
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      # MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DB: servo

volumes:
  servo-db: