name: CI/CD


on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

  workflow_dispatch:
  
env:
   LOGIN: ${{ secrets.DOCKER_LOGIN }}
   NAME: ${{ secrets.DOCKER_NAME }}

jobs:

  build_and_push_docker_image:
  
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
        
  deploy:
    needs: [build_and_push_docker_image]
    runs-on: ubuntu-latest
    
    steps: 
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: uptime
